openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /article:
    get:
      description: "Returns all articles"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "json"
              examples:
                Example#1:
                  value: [{
                    "id": 1,
                    "title": "The ansia to develop!",
                    "body": "...it's what keeps me going."
                  }]
components:
  schemas:
